version: '3'
services:
  screen_capture:
    container_name: 'screen_capture'
    image: 'screen_capture'
    volumes:
      - .:/app
      - ./drivers:/root/.wdm/drivers/
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - HOST=0.0.0.0
