version: '3'
services:
  screen_capture:
    container_name: 'screen_capture'
    image: 'screen_capture'
    volumes:
      - .:/app
      - ./drivers:/root/.wdm/drivers/
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - ALLOW_HOST=0.0.0.0
      - BUCKET_NAME=vrchat
#    networks:
#      - my_network
#networks:
#  my_network:
#    external: true